version: '3'

services:
  hbase:
    image: wsmt/hbase-standalone:2.0.1
    container_name: wsmt-hbase

  postgres:
    image: postgres:10.4
    container_name: wsmt-postgres
    volumes:
        - ./docker/init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: wsmt
      POSTGRES_USER: wsmt
      POSTGRES_PASSWORD: wsmt

  pixel-tracker:
    image: openjdk:8-jre-slim
    container_name: wsmt-pixel-tracker
    command: "java -agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=5005 -jar /opt/pixel-tracker/pixel-tracker.jar"
    depends_on:
      - hbase
    ports:
      - "8080:8080"
      - "5005:5005"
    volumes:
      - ./modules/pixel-tracker/target/pixel-tracker.jar:/opt/pixel-tracker/pixel-tracker.jar

  demo:
    image: openjdk:8-jre-slim
    container_name: wsmt-demo
    command: "java -jar /opt/demo/demo.jar"
    depends_on:
      - pixel-tracker
    ports:
      - "8081:8080"
    volumes:
      - ./modules/demo/target/demo.jar:/opt/demo/demo.jar

  reporter:
    image: openjdk:8-jre-slim
    container_name: wsmt-reporter
    command: "java -jar /opt/reporter/reporter.jar /opt/reporter/reporter.conf"
#    restart: unless-stopped
    depends_on:
      - hbase
      - postgres
    volumes:
      - ./modules/reporter/target/reporter.jar:/opt/reporter/reporter.jar
      - ./modules/reporter/application.conf:/opt/reporter/reporter.conf

  api:
    image: openjdk:8-jre-slim
    container_name: wsmt-api
    command: "java -agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=5005 -jar /opt/api/api.jar"
    depends_on:
      - postgres
    ports:
      - "8082:8080"
      - "5006:5005"
    volumes:
      - ./modules/api/target/api.jar:/opt/api/api.jar

  admin:
    image: openjdk:8-jre-slim
    container_name: wsmt-admin
    command: "java -jar /opt/admin/admin.jar"
    depends_on:
      - api
    ports:
      - "8083:8080"
    volumes:
      - ./modules/admin/target/admin.jar:/opt/admin/admin.jar